// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TrafficAnalytics.proto

package hu.traffic_analyser;

public final class TrafficAnalyticsClass {
  private TrafficAnalyticsClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TrafficAnalyticsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TrafficAnalytics.TrafficAnalytics)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string car_id = 1;</code>
     *
     * <pre>
     * car identification
     * </pre>
     */
    boolean hasCarId();
    /**
     * <code>required string car_id = 1;</code>
     *
     * <pre>
     * car identification
     * </pre>
     */
    java.lang.String getCarId();
    /**
     * <code>required string car_id = 1;</code>
     *
     * <pre>
     * car identification
     * </pre>
     */
    com.google.protobuf.ByteString
        getCarIdBytes();

    /**
     * <code>required string timestamp = 2;</code>
     *
     * <pre>
     * timestamp
     * </pre>
     */
    boolean hasTimestamp();
    /**
     * <code>required string timestamp = 2;</code>
     *
     * <pre>
     * timestamp
     * </pre>
     */
    java.lang.String getTimestamp();
    /**
     * <code>required string timestamp = 2;</code>
     *
     * <pre>
     * timestamp
     * </pre>
     */
    com.google.protobuf.ByteString
        getTimestampBytes();

    /**
     * <code>required .TrafficAnalytics.TrafficAnalytics.LatitudeNS latitudens = 3;</code>
     *
     * <pre>
     * position
     * </pre>
     */
    boolean hasLatitudens();
    /**
     * <code>required .TrafficAnalytics.TrafficAnalytics.LatitudeNS latitudens = 3;</code>
     *
     * <pre>
     * position
     * </pre>
     */
    hu.traffic_analyser.TrafficAnalyticsClass.TrafficAnalytics.LatitudeNS getLatitudens();

    /**
     * <code>required double latitude = 4;</code>
     */
    boolean hasLatitude();
    /**
     * <code>required double latitude = 4;</code>
     */
    double getLatitude();

    /**
     * <code>required .TrafficAnalytics.TrafficAnalytics.longitudeEW longitudeew = 5;</code>
     */
    boolean hasLongitudeew();
    /**
     * <code>required .TrafficAnalytics.TrafficAnalytics.longitudeEW longitudeew = 5;</code>
     */
    hu.traffic_analyser.TrafficAnalyticsClass.TrafficAnalytics.longitudeEW getLongitudeew();

    /**
     * <code>required double longitude = 6;</code>
     */
    boolean hasLongitude();
    /**
     * <code>required double longitude = 6;</code>
     */
    double getLongitude();

    /**
     * <code>required double density = 7;</code>
     *
     * <pre>
     * density
     * </pre>
     */
    boolean hasDensity();
    /**
     * <code>required double density = 7;</code>
     *
     * <pre>
     * density
     * </pre>
     */
    double getDensity();

    /**
     * <code>required uint32 vehicle_speed_gps = 8;</code>
     *
     * <pre>
     * vehicle speed (gps)
     * </pre>
     */
    boolean hasVehicleSpeedGps();
    /**
     * <code>required uint32 vehicle_speed_gps = 8;</code>
     *
     * <pre>
     * vehicle speed (gps)
     * </pre>
     */
    int getVehicleSpeedGps();

    /**
     * <code>optional uint32 vehicle_speed_can = 9;</code>
     *
     * <pre>
     * vehicle speed (can)
     * </pre>
     */
    boolean hasVehicleSpeedCan();
    /**
     * <code>optional uint32 vehicle_speed_can = 9;</code>
     *
     * <pre>
     * vehicle speed (can)
     * </pre>
     */
    int getVehicleSpeedCan();

    /**
     * <code>optional uint32 fuel_level = 10;</code>
     *
     * <pre>
     *fuel level (can)
     * </pre>
     */
    boolean hasFuelLevel();
    /**
     * <code>optional uint32 fuel_level = 10;</code>
     *
     * <pre>
     *fuel level (can)
     * </pre>
     */
    int getFuelLevel();
  }
  /**
   * Protobuf type {@code TrafficAnalytics.TrafficAnalytics}
   */
  public  static final class TrafficAnalytics extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:TrafficAnalytics.TrafficAnalytics)
      TrafficAnalyticsOrBuilder {
    // Use TrafficAnalytics.newBuilder() to construct.
    private TrafficAnalytics(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private TrafficAnalytics() {
      carId_ = "";
      timestamp_ = "";
      latitudens_ = 0;
      latitude_ = 0D;
      longitudeew_ = 0;
      longitude_ = 0D;
      density_ = 0D;
      vehicleSpeedGps_ = 0;
      vehicleSpeedCan_ = 0;
      fuelLevel_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TrafficAnalytics(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              carId_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              timestamp_ = bs;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              hu.traffic_analyser.TrafficAnalyticsClass.TrafficAnalytics.LatitudeNS value = hu.traffic_analyser.TrafficAnalyticsClass.TrafficAnalytics.LatitudeNS.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                latitudens_ = rawValue;
              }
              break;
            }
            case 33: {
              bitField0_ |= 0x00000008;
              latitude_ = input.readDouble();
              break;
            }
            case 40: {
              int rawValue = input.readEnum();
              hu.traffic_analyser.TrafficAnalyticsClass.TrafficAnalytics.longitudeEW value = hu.traffic_analyser.TrafficAnalyticsClass.TrafficAnalytics.longitudeEW.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(5, rawValue);
              } else {
                bitField0_ |= 0x00000010;
                longitudeew_ = rawValue;
              }
              break;
            }
            case 49: {
              bitField0_ |= 0x00000020;
              longitude_ = input.readDouble();
              break;
            }
            case 57: {
              bitField0_ |= 0x00000040;
              density_ = input.readDouble();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              vehicleSpeedGps_ = input.readUInt32();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              vehicleSpeedCan_ = input.readUInt32();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000200;
              fuelLevel_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return hu.traffic_analyser.TrafficAnalyticsClass.internal_static_TrafficAnalytics_TrafficAnalytics_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return hu.traffic_analyser.TrafficAnalyticsClass.internal_static_TrafficAnalytics_TrafficAnalytics_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              hu.traffic_analyser.TrafficAnalyticsClass.TrafficAnalytics.class, hu.traffic_analyser.TrafficAnalyticsClass.TrafficAnalytics.Builder.class);
    }

    /**
     * Protobuf enum {@code TrafficAnalytics.TrafficAnalytics.LatitudeNS}
     */
    public enum LatitudeNS
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>NORTH = 0;</code>
       */
      NORTH(0, 0),
      /**
       * <code>SOUTH = 1;</code>
       */
      SOUTH(1, 1),
      ;

      /**
       * <code>NORTH = 0;</code>
       */
      public static final int NORTH_VALUE = 0;
      /**
       * <code>SOUTH = 1;</code>
       */
      public static final int SOUTH_VALUE = 1;


      public final int getNumber() {
        return value;
      }

      public static LatitudeNS valueOf(int value) {
        switch (value) {
          case 0: return NORTH;
          case 1: return SOUTH;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<LatitudeNS>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<LatitudeNS>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<LatitudeNS>() {
              public LatitudeNS findValueByNumber(int number) {
                return LatitudeNS.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return hu.traffic_analyser.TrafficAnalyticsClass.TrafficAnalytics.getDescriptor().getEnumTypes().get(0);
      }

      private static final LatitudeNS[] VALUES = values();

      public static LatitudeNS valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private LatitudeNS(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:TrafficAnalytics.TrafficAnalytics.LatitudeNS)
    }

    /**
     * Protobuf enum {@code TrafficAnalytics.TrafficAnalytics.longitudeEW}
     */
    public enum longitudeEW
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>EAST = 0;</code>
       */
      EAST(0, 0),
      /**
       * <code>WEST = 1;</code>
       */
      WEST(1, 1),
      ;

      /**
       * <code>EAST = 0;</code>
       */
      public static final int EAST_VALUE = 0;
      /**
       * <code>WEST = 1;</code>
       */
      public static final int WEST_VALUE = 1;


      public final int getNumber() {
        return value;
      }

      public static longitudeEW valueOf(int value) {
        switch (value) {
          case 0: return EAST;
          case 1: return WEST;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<longitudeEW>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<longitudeEW>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<longitudeEW>() {
              public longitudeEW findValueByNumber(int number) {
                return longitudeEW.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return hu.traffic_analyser.TrafficAnalyticsClass.TrafficAnalytics.getDescriptor().getEnumTypes().get(1);
      }

      private static final longitudeEW[] VALUES = values();

      public static longitudeEW valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private longitudeEW(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:TrafficAnalytics.TrafficAnalytics.longitudeEW)
    }

    private int bitField0_;
    public static final int CAR_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object carId_;
    /**
     * <code>required string car_id = 1;</code>
     *
     * <pre>
     * car identification
     * </pre>
     */
    public boolean hasCarId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string car_id = 1;</code>
     *
     * <pre>
     * car identification
     * </pre>
     */
    public java.lang.String getCarId() {
      java.lang.Object ref = carId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          carId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string car_id = 1;</code>
     *
     * <pre>
     * car identification
     * </pre>
     */
    public com.google.protobuf.ByteString
        getCarIdBytes() {
      java.lang.Object ref = carId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        carId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private volatile java.lang.Object timestamp_;
    /**
     * <code>required string timestamp = 2;</code>
     *
     * <pre>
     * timestamp
     * </pre>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string timestamp = 2;</code>
     *
     * <pre>
     * timestamp
     * </pre>
     */
    public java.lang.String getTimestamp() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          timestamp_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string timestamp = 2;</code>
     *
     * <pre>
     * timestamp
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTimestampBytes() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timestamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LATITUDENS_FIELD_NUMBER = 3;
    private int latitudens_;
    /**
     * <code>required .TrafficAnalytics.TrafficAnalytics.LatitudeNS latitudens = 3;</code>
     *
     * <pre>
     * position
     * </pre>
     */
    public boolean hasLatitudens() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required .TrafficAnalytics.TrafficAnalytics.LatitudeNS latitudens = 3;</code>
     *
     * <pre>
     * position
     * </pre>
     */
    public hu.traffic_analyser.TrafficAnalyticsClass.TrafficAnalytics.LatitudeNS getLatitudens() {
      hu.traffic_analyser.TrafficAnalyticsClass.TrafficAnalytics.LatitudeNS result = hu.traffic_analyser.TrafficAnalyticsClass.TrafficAnalytics.LatitudeNS.valueOf(latitudens_);
      return result == null ? hu.traffic_analyser.TrafficAnalyticsClass.TrafficAnalytics.LatitudeNS.NORTH : result;
    }

    public static final int LATITUDE_FIELD_NUMBER = 4;
    private double latitude_;
    /**
     * <code>required double latitude = 4;</code>
     */
    public boolean hasLatitude() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required double latitude = 4;</code>
     */
    public double getLatitude() {
      return latitude_;
    }

    public static final int LONGITUDEEW_FIELD_NUMBER = 5;
    private int longitudeew_;
    /**
     * <code>required .TrafficAnalytics.TrafficAnalytics.longitudeEW longitudeew = 5;</code>
     */
    public boolean hasLongitudeew() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required .TrafficAnalytics.TrafficAnalytics.longitudeEW longitudeew = 5;</code>
     */
    public hu.traffic_analyser.TrafficAnalyticsClass.TrafficAnalytics.longitudeEW getLongitudeew() {
      hu.traffic_analyser.TrafficAnalyticsClass.TrafficAnalytics.longitudeEW result = hu.traffic_analyser.TrafficAnalyticsClass.TrafficAnalytics.longitudeEW.valueOf(longitudeew_);
      return result == null ? hu.traffic_analyser.TrafficAnalyticsClass.TrafficAnalytics.longitudeEW.EAST : result;
    }

    public static final int LONGITUDE_FIELD_NUMBER = 6;
    private double longitude_;
    /**
     * <code>required double longitude = 6;</code>
     */
    public boolean hasLongitude() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required double longitude = 6;</code>
     */
    public double getLongitude() {
      return longitude_;
    }

    public static final int DENSITY_FIELD_NUMBER = 7;
    private double density_;
    /**
     * <code>required double density = 7;</code>
     *
     * <pre>
     * density
     * </pre>
     */
    public boolean hasDensity() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required double density = 7;</code>
     *
     * <pre>
     * density
     * </pre>
     */
    public double getDensity() {
      return density_;
    }

    public static final int VEHICLE_SPEED_GPS_FIELD_NUMBER = 8;
    private int vehicleSpeedGps_;
    /**
     * <code>required uint32 vehicle_speed_gps = 8;</code>
     *
     * <pre>
     * vehicle speed (gps)
     * </pre>
     */
    public boolean hasVehicleSpeedGps() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>required uint32 vehicle_speed_gps = 8;</code>
     *
     * <pre>
     * vehicle speed (gps)
     * </pre>
     */
    public int getVehicleSpeedGps() {
      return vehicleSpeedGps_;
    }

    public static final int VEHICLE_SPEED_CAN_FIELD_NUMBER = 9;
    private int vehicleSpeedCan_;
    /**
     * <code>optional uint32 vehicle_speed_can = 9;</code>
     *
     * <pre>
     * vehicle speed (can)
     * </pre>
     */
    public boolean hasVehicleSpeedCan() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional uint32 vehicle_speed_can = 9;</code>
     *
     * <pre>
     * vehicle speed (can)
     * </pre>
     */
    public int getVehicleSpeedCan() {
      return vehicleSpeedCan_;
    }

    public static final int FUEL_LEVEL_FIELD_NUMBER = 10;
    private int fuelLevel_;
    /**
     * <code>optional uint32 fuel_level = 10;</code>
     *
     * <pre>
     *fuel level (can)
     * </pre>
     */
    public boolean hasFuelLevel() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional uint32 fuel_level = 10;</code>
     *
     * <pre>
     *fuel level (can)
     * </pre>
     */
    public int getFuelLevel() {
      return fuelLevel_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasCarId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLatitudens()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLatitude()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLongitudeew()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLongitude()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDensity()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVehicleSpeedGps()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getCarIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTimestampBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, latitudens_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeDouble(4, latitude_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeEnum(5, longitudeew_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeDouble(6, longitude_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeDouble(7, density_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeUInt32(8, vehicleSpeedGps_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeUInt32(9, vehicleSpeedCan_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeUInt32(10, fuelLevel_);
      }
      unknownFields.writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getCarIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTimestampBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, latitudens_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, latitude_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, longitudeew_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, longitude_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(7, density_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(8, vehicleSpeedGps_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(9, vehicleSpeedCan_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(10, fuelLevel_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static hu.traffic_analyser.TrafficAnalyticsClass.TrafficAnalytics parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hu.traffic_analyser.TrafficAnalyticsClass.TrafficAnalytics parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hu.traffic_analyser.TrafficAnalyticsClass.TrafficAnalytics parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hu.traffic_analyser.TrafficAnalyticsClass.TrafficAnalytics parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hu.traffic_analyser.TrafficAnalyticsClass.TrafficAnalytics parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static hu.traffic_analyser.TrafficAnalyticsClass.TrafficAnalytics parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static hu.traffic_analyser.TrafficAnalyticsClass.TrafficAnalytics parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static hu.traffic_analyser.TrafficAnalyticsClass.TrafficAnalytics parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static hu.traffic_analyser.TrafficAnalyticsClass.TrafficAnalytics parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static hu.traffic_analyser.TrafficAnalyticsClass.TrafficAnalytics parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(hu.traffic_analyser.TrafficAnalyticsClass.TrafficAnalytics prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TrafficAnalytics.TrafficAnalytics}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TrafficAnalytics.TrafficAnalytics)
        hu.traffic_analyser.TrafficAnalyticsClass.TrafficAnalyticsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return hu.traffic_analyser.TrafficAnalyticsClass.internal_static_TrafficAnalytics_TrafficAnalytics_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return hu.traffic_analyser.TrafficAnalyticsClass.internal_static_TrafficAnalytics_TrafficAnalytics_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                hu.traffic_analyser.TrafficAnalyticsClass.TrafficAnalytics.class, hu.traffic_analyser.TrafficAnalyticsClass.TrafficAnalytics.Builder.class);
      }

      // Construct using hu.traffic_analyser.TrafficAnalyticsClass.TrafficAnalytics.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        carId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        latitudens_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        latitude_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000008);
        longitudeew_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        longitude_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000020);
        density_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000040);
        vehicleSpeedGps_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        vehicleSpeedCan_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        fuelLevel_ = 0;
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return hu.traffic_analyser.TrafficAnalyticsClass.internal_static_TrafficAnalytics_TrafficAnalytics_descriptor;
      }

      public hu.traffic_analyser.TrafficAnalyticsClass.TrafficAnalytics getDefaultInstanceForType() {
        return hu.traffic_analyser.TrafficAnalyticsClass.TrafficAnalytics.getDefaultInstance();
      }

      public hu.traffic_analyser.TrafficAnalyticsClass.TrafficAnalytics build() {
        hu.traffic_analyser.TrafficAnalyticsClass.TrafficAnalytics result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public hu.traffic_analyser.TrafficAnalyticsClass.TrafficAnalytics buildPartial() {
        hu.traffic_analyser.TrafficAnalyticsClass.TrafficAnalytics result = new hu.traffic_analyser.TrafficAnalyticsClass.TrafficAnalytics(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.carId_ = carId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.latitudens_ = latitudens_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.latitude_ = latitude_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.longitudeew_ = longitudeew_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.longitude_ = longitude_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.density_ = density_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.vehicleSpeedGps_ = vehicleSpeedGps_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.vehicleSpeedCan_ = vehicleSpeedCan_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.fuelLevel_ = fuelLevel_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof hu.traffic_analyser.TrafficAnalyticsClass.TrafficAnalytics) {
          return mergeFrom((hu.traffic_analyser.TrafficAnalyticsClass.TrafficAnalytics)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(hu.traffic_analyser.TrafficAnalyticsClass.TrafficAnalytics other) {
        if (other == hu.traffic_analyser.TrafficAnalyticsClass.TrafficAnalytics.getDefaultInstance()) return this;
        if (other.hasCarId()) {
          bitField0_ |= 0x00000001;
          carId_ = other.carId_;
          onChanged();
        }
        if (other.hasTimestamp()) {
          bitField0_ |= 0x00000002;
          timestamp_ = other.timestamp_;
          onChanged();
        }
        if (other.hasLatitudens()) {
          setLatitudens(other.getLatitudens());
        }
        if (other.hasLatitude()) {
          setLatitude(other.getLatitude());
        }
        if (other.hasLongitudeew()) {
          setLongitudeew(other.getLongitudeew());
        }
        if (other.hasLongitude()) {
          setLongitude(other.getLongitude());
        }
        if (other.hasDensity()) {
          setDensity(other.getDensity());
        }
        if (other.hasVehicleSpeedGps()) {
          setVehicleSpeedGps(other.getVehicleSpeedGps());
        }
        if (other.hasVehicleSpeedCan()) {
          setVehicleSpeedCan(other.getVehicleSpeedCan());
        }
        if (other.hasFuelLevel()) {
          setFuelLevel(other.getFuelLevel());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCarId()) {
          return false;
        }
        if (!hasTimestamp()) {
          return false;
        }
        if (!hasLatitudens()) {
          return false;
        }
        if (!hasLatitude()) {
          return false;
        }
        if (!hasLongitudeew()) {
          return false;
        }
        if (!hasLongitude()) {
          return false;
        }
        if (!hasDensity()) {
          return false;
        }
        if (!hasVehicleSpeedGps()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        hu.traffic_analyser.TrafficAnalyticsClass.TrafficAnalytics parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (hu.traffic_analyser.TrafficAnalyticsClass.TrafficAnalytics) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object carId_ = "";
      /**
       * <code>required string car_id = 1;</code>
       *
       * <pre>
       * car identification
       * </pre>
       */
      public boolean hasCarId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string car_id = 1;</code>
       *
       * <pre>
       * car identification
       * </pre>
       */
      public java.lang.String getCarId() {
        java.lang.Object ref = carId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            carId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string car_id = 1;</code>
       *
       * <pre>
       * car identification
       * </pre>
       */
      public com.google.protobuf.ByteString
          getCarIdBytes() {
        java.lang.Object ref = carId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          carId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string car_id = 1;</code>
       *
       * <pre>
       * car identification
       * </pre>
       */
      public Builder setCarId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        carId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string car_id = 1;</code>
       *
       * <pre>
       * car identification
       * </pre>
       */
      public Builder clearCarId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        carId_ = getDefaultInstance().getCarId();
        onChanged();
        return this;
      }
      /**
       * <code>required string car_id = 1;</code>
       *
       * <pre>
       * car identification
       * </pre>
       */
      public Builder setCarIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        carId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object timestamp_ = "";
      /**
       * <code>required string timestamp = 2;</code>
       *
       * <pre>
       * timestamp
       * </pre>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string timestamp = 2;</code>
       *
       * <pre>
       * timestamp
       * </pre>
       */
      public java.lang.String getTimestamp() {
        java.lang.Object ref = timestamp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            timestamp_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string timestamp = 2;</code>
       *
       * <pre>
       * timestamp
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTimestampBytes() {
        java.lang.Object ref = timestamp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          timestamp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string timestamp = 2;</code>
       *
       * <pre>
       * timestamp
       * </pre>
       */
      public Builder setTimestamp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string timestamp = 2;</code>
       *
       * <pre>
       * timestamp
       * </pre>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = getDefaultInstance().getTimestamp();
        onChanged();
        return this;
      }
      /**
       * <code>required string timestamp = 2;</code>
       *
       * <pre>
       * timestamp
       * </pre>
       */
      public Builder setTimestampBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        timestamp_ = value;
        onChanged();
        return this;
      }

      private int latitudens_ = 0;
      /**
       * <code>required .TrafficAnalytics.TrafficAnalytics.LatitudeNS latitudens = 3;</code>
       *
       * <pre>
       * position
       * </pre>
       */
      public boolean hasLatitudens() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required .TrafficAnalytics.TrafficAnalytics.LatitudeNS latitudens = 3;</code>
       *
       * <pre>
       * position
       * </pre>
       */
      public hu.traffic_analyser.TrafficAnalyticsClass.TrafficAnalytics.LatitudeNS getLatitudens() {
        hu.traffic_analyser.TrafficAnalyticsClass.TrafficAnalytics.LatitudeNS result = hu.traffic_analyser.TrafficAnalyticsClass.TrafficAnalytics.LatitudeNS.valueOf(latitudens_);
        return result == null ? hu.traffic_analyser.TrafficAnalyticsClass.TrafficAnalytics.LatitudeNS.NORTH : result;
      }
      /**
       * <code>required .TrafficAnalytics.TrafficAnalytics.LatitudeNS latitudens = 3;</code>
       *
       * <pre>
       * position
       * </pre>
       */
      public Builder setLatitudens(hu.traffic_analyser.TrafficAnalyticsClass.TrafficAnalytics.LatitudeNS value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        latitudens_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .TrafficAnalytics.TrafficAnalytics.LatitudeNS latitudens = 3;</code>
       *
       * <pre>
       * position
       * </pre>
       */
      public Builder clearLatitudens() {
        bitField0_ = (bitField0_ & ~0x00000004);
        latitudens_ = 0;
        onChanged();
        return this;
      }

      private double latitude_ ;
      /**
       * <code>required double latitude = 4;</code>
       */
      public boolean hasLatitude() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required double latitude = 4;</code>
       */
      public double getLatitude() {
        return latitude_;
      }
      /**
       * <code>required double latitude = 4;</code>
       */
      public Builder setLatitude(double value) {
        bitField0_ |= 0x00000008;
        latitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double latitude = 4;</code>
       */
      public Builder clearLatitude() {
        bitField0_ = (bitField0_ & ~0x00000008);
        latitude_ = 0D;
        onChanged();
        return this;
      }

      private int longitudeew_ = 0;
      /**
       * <code>required .TrafficAnalytics.TrafficAnalytics.longitudeEW longitudeew = 5;</code>
       */
      public boolean hasLongitudeew() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required .TrafficAnalytics.TrafficAnalytics.longitudeEW longitudeew = 5;</code>
       */
      public hu.traffic_analyser.TrafficAnalyticsClass.TrafficAnalytics.longitudeEW getLongitudeew() {
        hu.traffic_analyser.TrafficAnalyticsClass.TrafficAnalytics.longitudeEW result = hu.traffic_analyser.TrafficAnalyticsClass.TrafficAnalytics.longitudeEW.valueOf(longitudeew_);
        return result == null ? hu.traffic_analyser.TrafficAnalyticsClass.TrafficAnalytics.longitudeEW.EAST : result;
      }
      /**
       * <code>required .TrafficAnalytics.TrafficAnalytics.longitudeEW longitudeew = 5;</code>
       */
      public Builder setLongitudeew(hu.traffic_analyser.TrafficAnalyticsClass.TrafficAnalytics.longitudeEW value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        longitudeew_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .TrafficAnalytics.TrafficAnalytics.longitudeEW longitudeew = 5;</code>
       */
      public Builder clearLongitudeew() {
        bitField0_ = (bitField0_ & ~0x00000010);
        longitudeew_ = 0;
        onChanged();
        return this;
      }

      private double longitude_ ;
      /**
       * <code>required double longitude = 6;</code>
       */
      public boolean hasLongitude() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required double longitude = 6;</code>
       */
      public double getLongitude() {
        return longitude_;
      }
      /**
       * <code>required double longitude = 6;</code>
       */
      public Builder setLongitude(double value) {
        bitField0_ |= 0x00000020;
        longitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double longitude = 6;</code>
       */
      public Builder clearLongitude() {
        bitField0_ = (bitField0_ & ~0x00000020);
        longitude_ = 0D;
        onChanged();
        return this;
      }

      private double density_ ;
      /**
       * <code>required double density = 7;</code>
       *
       * <pre>
       * density
       * </pre>
       */
      public boolean hasDensity() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required double density = 7;</code>
       *
       * <pre>
       * density
       * </pre>
       */
      public double getDensity() {
        return density_;
      }
      /**
       * <code>required double density = 7;</code>
       *
       * <pre>
       * density
       * </pre>
       */
      public Builder setDensity(double value) {
        bitField0_ |= 0x00000040;
        density_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double density = 7;</code>
       *
       * <pre>
       * density
       * </pre>
       */
      public Builder clearDensity() {
        bitField0_ = (bitField0_ & ~0x00000040);
        density_ = 0D;
        onChanged();
        return this;
      }

      private int vehicleSpeedGps_ ;
      /**
       * <code>required uint32 vehicle_speed_gps = 8;</code>
       *
       * <pre>
       * vehicle speed (gps)
       * </pre>
       */
      public boolean hasVehicleSpeedGps() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required uint32 vehicle_speed_gps = 8;</code>
       *
       * <pre>
       * vehicle speed (gps)
       * </pre>
       */
      public int getVehicleSpeedGps() {
        return vehicleSpeedGps_;
      }
      /**
       * <code>required uint32 vehicle_speed_gps = 8;</code>
       *
       * <pre>
       * vehicle speed (gps)
       * </pre>
       */
      public Builder setVehicleSpeedGps(int value) {
        bitField0_ |= 0x00000080;
        vehicleSpeedGps_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 vehicle_speed_gps = 8;</code>
       *
       * <pre>
       * vehicle speed (gps)
       * </pre>
       */
      public Builder clearVehicleSpeedGps() {
        bitField0_ = (bitField0_ & ~0x00000080);
        vehicleSpeedGps_ = 0;
        onChanged();
        return this;
      }

      private int vehicleSpeedCan_ ;
      /**
       * <code>optional uint32 vehicle_speed_can = 9;</code>
       *
       * <pre>
       * vehicle speed (can)
       * </pre>
       */
      public boolean hasVehicleSpeedCan() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional uint32 vehicle_speed_can = 9;</code>
       *
       * <pre>
       * vehicle speed (can)
       * </pre>
       */
      public int getVehicleSpeedCan() {
        return vehicleSpeedCan_;
      }
      /**
       * <code>optional uint32 vehicle_speed_can = 9;</code>
       *
       * <pre>
       * vehicle speed (can)
       * </pre>
       */
      public Builder setVehicleSpeedCan(int value) {
        bitField0_ |= 0x00000100;
        vehicleSpeedCan_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 vehicle_speed_can = 9;</code>
       *
       * <pre>
       * vehicle speed (can)
       * </pre>
       */
      public Builder clearVehicleSpeedCan() {
        bitField0_ = (bitField0_ & ~0x00000100);
        vehicleSpeedCan_ = 0;
        onChanged();
        return this;
      }

      private int fuelLevel_ ;
      /**
       * <code>optional uint32 fuel_level = 10;</code>
       *
       * <pre>
       *fuel level (can)
       * </pre>
       */
      public boolean hasFuelLevel() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional uint32 fuel_level = 10;</code>
       *
       * <pre>
       *fuel level (can)
       * </pre>
       */
      public int getFuelLevel() {
        return fuelLevel_;
      }
      /**
       * <code>optional uint32 fuel_level = 10;</code>
       *
       * <pre>
       *fuel level (can)
       * </pre>
       */
      public Builder setFuelLevel(int value) {
        bitField0_ |= 0x00000200;
        fuelLevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 fuel_level = 10;</code>
       *
       * <pre>
       *fuel level (can)
       * </pre>
       */
      public Builder clearFuelLevel() {
        bitField0_ = (bitField0_ & ~0x00000200);
        fuelLevel_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:TrafficAnalytics.TrafficAnalytics)
    }

    // @@protoc_insertion_point(class_scope:TrafficAnalytics.TrafficAnalytics)
    private static final hu.traffic_analyser.TrafficAnalyticsClass.TrafficAnalytics DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new hu.traffic_analyser.TrafficAnalyticsClass.TrafficAnalytics();
    }

    public static hu.traffic_analyser.TrafficAnalyticsClass.TrafficAnalytics getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static final com.google.protobuf.Parser<TrafficAnalytics> PARSER =
        new com.google.protobuf.AbstractParser<TrafficAnalytics>() {
      public TrafficAnalytics parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new TrafficAnalytics(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TrafficAnalytics> getParserForType() {
      return PARSER;
    }

    public hu.traffic_analyser.TrafficAnalyticsClass.TrafficAnalytics getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_TrafficAnalytics_TrafficAnalytics_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_TrafficAnalytics_TrafficAnalytics_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026TrafficAnalytics.proto\022\020TrafficAnalyti" +
      "cs\"\204\003\n\020TrafficAnalytics\022\016\n\006car_id\030\001 \002(\t\022" +
      "\021\n\ttimestamp\030\002 \002(\t\022A\n\nlatitudens\030\003 \002(\0162-" +
      ".TrafficAnalytics.TrafficAnalytics.Latit" +
      "udeNS\022\020\n\010latitude\030\004 \002(\001\022C\n\013longitudeew\030\005" +
      " \002(\0162..TrafficAnalytics.TrafficAnalytics" +
      ".longitudeEW\022\021\n\tlongitude\030\006 \002(\001\022\017\n\007densi" +
      "ty\030\007 \002(\001\022\031\n\021vehicle_speed_gps\030\010 \002(\r\022\031\n\021v" +
      "ehicle_speed_can\030\t \001(\r\022\022\n\nfuel_level\030\n \001" +
      "(\r\"\"\n\nLatitudeNS\022\t\n\005NORTH\020\000\022\t\n\005SOUTH\020\001\"!",
      "\n\013longitudeEW\022\010\n\004EAST\020\000\022\010\n\004WEST\020\001B,\n\023hu." +
      "traffic_analyserB\025TrafficAnalyticsClass"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_TrafficAnalytics_TrafficAnalytics_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TrafficAnalytics_TrafficAnalytics_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_TrafficAnalytics_TrafficAnalytics_descriptor,
        new java.lang.String[] { "CarId", "Timestamp", "Latitudens", "Latitude", "Longitudeew", "Longitude", "Density", "VehicleSpeedGps", "VehicleSpeedCan", "FuelLevel", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
